CREATE DATABASE Relationship

CREATE TABLE Passports(
PassportID INT PRIMARY KEY NOT NULL IDENTITY(101,1),
PassportNumber VARCHAR(8) NOT NULL
)

CREATE TABLE Persons(
PersonID INT PRIMARY KEY NOT NULL IDENTITY,
FirstName VARCHAR(20) NOT NULL,
Salary DECIMAL(8,2),
PassportID INT FOREIGN KEY REFERENCES Passports(PassportID) NOT NULL UNIQUE
)

INSERT INTO Passports(PassportNumber)
VALUES
('N34FG21B'),
('K65LO4R7'),
('ZE657QP2')

INSERT INTO Persons(FirstName, Salary, PassportID)
VALUES
('Roberto', 43300.00, 102),
('Tom', 56100.00, 103),
('Yana', 60200.00, 101)


